name: Update Issue Labels

on:
  issues:
    types:
      - closed

jobs:
  remove-wip-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'ðŸš§ Work in Progress' label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ðŸš§ Work in Progress
