name: Test, Format & Analyze

on:
  push:

jobs:
  analyze:
    name: Test, Format & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: RubberDuckCrew/github_flutter
          path: github_flutter

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{vars.FLUTTER_CHANNEL}}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Format check
        working-directory: app
        run: dart format --set-exit-if-changed .

      - name: Analyze
        working-directory: app
        run: flutter analyze

      - name: Run tests
        working-directory: app
        run: flutter test